message: This is the development environment
server:
  port: 8087
#  address: 0.0.0.0

spring:
  application:
    name: gzhuoj-user-service

  cloud:
    ## consul 服务端治理设置
    consul:
      host: 47.121.209.33
      port: 8500
      discovery:
        ## 注册到consul的服务名称
        service-name: gzhuoj-user-service
        heartbeat:
          enabled: true
        prefer-ip-address: true # 使用容器的外部IP地址进行注册
  ## 数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.121.209.33:3307/gzhuoj-user?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

