#server:
#  port: 8009


spring:
  application:
    name: gzhuoj-user-service
  profiles:
    active: dev
  data:
    redis:
      host: 47.120.53.127
      port: 6379
      password: gzhuoj
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/*.xml

  # JWT相关配置
  gzhuoj:
    jwt:
      location: classpath:gzhuoj.jks
      alias: gzhuoj
      password: gzhuacm512
      tokenTTL: 30m
  #  auth:
