#server:
#  port: 8009
spring:
  application:
    name: gzhuoj-user-service
  profiles:
    active: dev
  data:
    redis:
      host: 47.121.209.33
      port: 6379
      password: gzhuoj
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/*.xml

batchImport:
  max_users: 300

# JWT相关配置
gzhuoj:
  jwt:
    location: classpath:gzhuoj.jks
    alias: gzhuoj
    password: gzhuoj
    tokenTTL: 3600m
#  auth:
