server:
  port: 8009

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gzhuoj_usr?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
