#server:
#  port: 8009
spring:
  application:
    name: gzhuoj-contest-service
  profiles:
    active: dev
  data:
    redis:
      host: 47.120.53.127
      port: 6379
      password: gzhuoj
Contest:
  max-file-num: 10
RegContest:
  max-gen-team: 500
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/*.xml

gzhuoj:
  jwt:
    location: classpath:gzhuoj.jks
    alias: gzhuoj
    password: gzhuoj
    tokenTTL: 30m
  judge:
    server-name: gzhuoj-judgeserver