spring:
  main:
    web-application-type: reactive
  application:
    name: gzhuoj-gateway
  profiles:
    active: dev
  data:
    redis:
      host: 47.121.209.33
      port: 6379
      password: gzhuoj
# JWT相关配置
gzhuoj:
  jwt:
    location: classpath:gzhuoj.jks
    alias:  gzhuoj
    password: gzhuoj
    tokenTTL: 30m
  auth:
    exclude-paths:
      - /api/gzhuoj-user/user/login
      - /api/gzhuoj-contest/regular/contest/login
