#server:
#  port: 8009
spring:
  application:
    name: gzhuoj-problem-service
  profiles:
    active: dev
  data:
    redis:
      host: 47.121.209.33
      port: 6379
      password: gzhuoj
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/*.xml
Judge:
  max-file-num: 10