server:
  port: 8088
spring:
  application:
    name: gzhuoj-judge-service
  profiles:
    active: dev
#    active: prd

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/*.xml