server:
  port: 8088
spring:
  application:
    name: gzhuoj-judge-service
  cloud:
    ## consul 服务端治理设置
    consul:
      host: 47.120.53.127
      port: 8500
      discovery:
        ## 注册到consul的服务名称
        service-name: gzhuoj-judge-service
        heartbeat:
          enabled: true
  data:
    redis:
      host: 47.120.53.127
      port: 6379
      password: gzhuoj
  datasource:
    username: root
    password: 3.14PAi#!
    url: jdbc:mysql://47.120.53.127:3307/gzhuoj-contest?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/*.xml

#本地
gzhuoj-judge-server:
  ip: localhost
  port: 8063
  max-task-num: -1
  name: gzhuoj-judge-1