# JWT相关配置
gzhuoj:
  jwt:
    location: classpath:gzhuoj.jks
    alias: gzhuoj
    password: gzhuoj
    tokenTTL: 30m
spring:
  data:
    redis:
      host: 47.120.53.127
      port: 6379
      password: gzhuoj